language: node_js
node_js:
  - "0.10"
services:
  - postgresql
addons:
  postgresql: "9.3"
  sauce_connect: true
notifications:
  email: false
before_script:
  - psql -c 'create database trainer_test;' -U postgres
  - cd test/scripts; ./create-db.sh trainer_test; cd ../..;
  # specify port here instead of in the ENV section so we don't 
  # have conflicts between node server for unit tests and this one.
  - PORT=9000 node server/index.js& # & on the end runs it in the background.
  - sleep 5 # wait for server to boot up
script:
  - npm run syntax
  - npm test
after_script:
  - npm run coveralls
  - npm run e2e
env:
  global:
    - DATABASE_URL=postgres://postgres@localhost/trainer_test
    - AWS_BUCKET=ab-trainer-test
    # AWS_SECRET_ACCESS_KEY
    - secure: "hDxMsB2NuJzuGQTUiKJ/Mky//PcXPMIVLa5Ye6yvTD3wzfvg/bm4juQQw0+5o114ytB625PWIh/vVb8d/z/JAqLnavS87WhzN6kvf/N/F6yTwZxq7MoCNMTsFrITLT/iYWWpnbV1wdZsSn3TodEOtPi666t4FF6nPZfGKgIyGt4="
    # AWS_ACCESS_KEY_ID
    - secure: "hGdnpHkEbBgjgQl0m6ZdxxU91HQVhtB1PyqF2CvCLWS5XSFQiduKUspU2jOyCj60QzXeHILt0qZ/WWtCkWLYw9Z4wa/SwpneVWtpRDpnJGU+ByQQTNa4+2o9T7YhTzGSltZWglbhrhXEhdRZdHDcf2TvvuZkMpAb72CgsOBfAVc="
    # SAUCE_USERNAME
    - secure: "TMeuqni3Foyx9h+ZfWfHCqpbZdmPUqS33E92Ju+PdezLuzOKuHs1jGLBs4c6AZ/4Zr/G1Qh5NP8qWp4hBU3UKWOn9I9/zR3qzv5My4567FMgxdb+BwrIImm4AMrvCPHSfVtoxcUQ7xSrbbsha1/B2Da3X/Lmp6nobT33K1mbCu4="
    # SAUCE_ACCESS_KEY
    - secure: "ReKXmX4VRSl8sLtpm1/mIfKkD2yU2fCA0L9gTaSNQs6F4ZvWfRO0LDSm7oZtStyR4VJpafmFi8kW4jhnlUgtL3zD+lG8vA/On+WUMAqjMYGF6Kxr3hIMf4nXf4xWihBSgw8lWiQG56MDgvoDkPR213ViCUOkshSP+jgeymprDzU="